name: icesspool_mobilev2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  enhance_stepper: ^0.1.1
  flutter_form_builder: ^7.7.0
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^3.0.1
  timeline_tile: ^2.0.0
  firebase_core: ^2.5.0
  geolocator: ^9.0.2
  get_storage: ^2.0.3
  sizer: ^2.0.15

dev_dependencies: 
 # flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

