// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-TKStHs1tVezSqI5G28vEGtcfHZUdy_4',
    appId: '1:373487309327:web:f7240945dc4d43f8ed097a',
    messagingSenderId: '373487309327',
    projectId: 'icesspool-3fa23',
    authDomain: 'icesspool-3fa23.firebaseapp.com',
    storageBucket: 'icesspool-3fa23.appspot.com',
    measurementId: 'G-DKPCZDV4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVMbO06VCW9SHin3QfAIZWOXwnqj_TLU',
    appId: '1:373487309327:android:36bc0b02a90fc528ed097a',
    messagingSenderId: '373487309327',
    projectId: 'icesspool-3fa23',
    storageBucket: 'icesspool-3fa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz69o-jjnR4ZXj_eZgdl4OfCbCAngGnxU',
    appId: '1:373487309327:ios:9325ab62400ab9b4ed097a',
    messagingSenderId: '373487309327',
    projectId: 'icesspool-3fa23',
    storageBucket: 'icesspool-3fa23.appspot.com',
    iosClientId: '373487309327-t9o6vs69fa2d0t95noh6tk5o7m54ldum.apps.googleusercontent.com',
    iosBundleId: 'com.icesspool.moobile.icesspoolMobilev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz69o-jjnR4ZXj_eZgdl4OfCbCAngGnxU',
    appId: '1:373487309327:ios:9325ab62400ab9b4ed097a',
    messagingSenderId: '373487309327',
    projectId: 'icesspool-3fa23',
    storageBucket: 'icesspool-3fa23.appspot.com',
    iosClientId: '373487309327-t9o6vs69fa2d0t95noh6tk5o7m54ldum.apps.googleusercontent.com',
    iosBundleId: 'com.icesspool.moobile.icesspoolMobilev2',
  );
}
