// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD26hgTlyRJRGjXtEgzu_NfrAxJMwKlpVo',
    appId: '1:137742446645:web:3767ff530dade669cd417c',
    messagingSenderId: '137742446645',
    projectId: 'icesspool-v2',
    authDomain: 'icesspool-v2.firebaseapp.com',
    storageBucket: 'icesspool-v2.appspot.com',
    measurementId: 'G-6VGC7511BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUjxYGNOxCNLWy5vCDefQe4VLiLkLZEqQ',
    appId: '1:137742446645:android:3fdf4848221b1290cd417c',
    messagingSenderId: '137742446645',
    projectId: 'icesspool-v2',
    storageBucket: 'icesspool-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_OKBkQ0FvTicioek5JFGy9d3cDzwpsI',
    appId: '1:137742446645:ios:5539f91b243bfd4ecd417c',
    messagingSenderId: '137742446645',
    projectId: 'icesspool-v2',
    storageBucket: 'icesspool-v2.appspot.com',
    iosClientId: '137742446645-0tnvntqrkb27pp3o6j8e3ruhe077s0tk.apps.googleusercontent.com',
    iosBundleId: 'com.icesspool.moobile.icesspoolMobilev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF_OKBkQ0FvTicioek5JFGy9d3cDzwpsI',
    appId: '1:137742446645:ios:5539f91b243bfd4ecd417c',
    messagingSenderId: '137742446645',
    projectId: 'icesspool-v2',
    storageBucket: 'icesspool-v2.appspot.com',
    iosClientId: '137742446645-0tnvntqrkb27pp3o6j8e3ruhe077s0tk.apps.googleusercontent.com',
    iosBundleId: 'com.icesspool.moobile.icesspoolMobilev2',
  );
}
